services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    command: bash -c "composer install && apache2-foreground"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge